-- 자유수영 1회 요금 채움 (원본 이용가격 재파싱)
update public.pools set price_free_swim=4000, prices=$j$[{"label": "1일권", "amount": 4000}]$j$::jsonb where name='조종 국민체육센터 수영장';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "1일권", "amount": 4000}]$j$::jsonb where name='청평호반문화체육센터';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "1일권", "amount": 4000}]$j$::jsonb where name='한석봉체육관';
update public.pools set price_free_swim=5000, prices=$j$[{"label": "1일권", "amount": 5000}]$j$::jsonb where name='강남스포츠문화센터';
update public.pools set price_free_swim=3500, prices=$j$[{"label": "평일", "amount": 3500}, {"label": "주말", "amount": 4000}]$j$::jsonb where name='고덕사회체육센터';
update public.pools set price_free_swim=4400, prices=$j$[{"label": "1일권", "amount": 4400}]$j$::jsonb where name='고덕어울림수영장';
update public.pools set price_free_swim=4400, prices=$j$[{"label": "1일권", "amount": 4400}]$j$::jsonb where name='온조대왕문화체육관';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "평일", "amount": 4000}, {"label": "주말", "amount": 4800}]$j$::jsonb where name='강북문화예술회관';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "평일", "amount": 4000}, {"label": "주말", "amount": 4800}]$j$::jsonb where name='강북웰빙스포츠센터';
update public.pools set price_free_swim=3500, prices=$j$[{"label": "평일", "amount": 3500}, {"label": "주말", "amount": 7000}]$j$::jsonb where name='강서구민올림픽체육센터';
update public.pools set price_free_swim=6000, prices=$j$[{"label": "1일권", "amount": 6000}]$j$::jsonb where name='강화군국민체육센터';
update public.pools set price_free_swim=3500, prices=$j$[{"label": "평일", "amount": 3500}, {"label": "주말", "amount": 4000}]$j$::jsonb where name='과천시민회관수영장';
update public.pools set price_free_swim=3500, prices=$j$[{"label": "평일", "amount": 3500}, {"label": "주말", "amount": 4000}]$j$::jsonb where name='과천시청소년수련관';
update public.pools set price_free_swim=3400, prices=$j$[{"label": "평일", "amount": 3400}, {"label": "주말", "amount": 4400}]$j$::jsonb where name='관악구민종합체육센터';
update public.pools set price_free_swim=3410, prices=$j$[{"label": "평일", "amount": 3410}, {"label": "주말", "amount": 4400}]$j$::jsonb where name='신림체육센터';
update public.pools set price_free_swim=3500, prices=$j$[{"label": "평일", "amount": 3500}]$j$::jsonb where name='광진구민체육센터';
update public.pools set price_free_swim=3500, prices=$j$[{"label": "1일권", "amount": 3500}]$j$::jsonb where name='광진문화예술회관';
update public.pools set price_free_swim=3500, prices=$j$[{"label": "1일권", "amount": 3500}]$j$::jsonb where name='중곡문화체육센터';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "평일", "amount": 4000}, {"label": "주말", "amount": 4500}]$j$::jsonb where name='50플러스수영장';
update public.pools set price_free_swim=3500, prices=$j$[{"label": "평일", "amount": 3500}, {"label": "주말", "amount": 4550}]$j$::jsonb where name='고척체육센터';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "평일", "amount": 4000}, {"label": "주말", "amount": 4500}]$j$::jsonb where name='구로구민체육센터';
update public.pools set price_free_swim=4500, prices=$j$[{"label": "1일권", "amount": 4500}]$j$::jsonb where name='신도림생활체육관';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}, {"label": "1일권", "amount": 4500}]$j$::jsonb where name='구리시민스포츠센터';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "평일", "amount": 4000}, {"label": "주말", "amount": 5200}]$j$::jsonb where name='남동수영장';
update public.pools set price_free_swim=3600, prices=$j$[{"label": "평일", "amount": 3600}, {"label": "주말", "amount": 4600}]$j$::jsonb where name='남양주체육문화센터';
update public.pools set price_free_swim=3600, prices=$j$[{"label": "평일", "amount": 3600}, {"label": "주말", "amount": 4600}]$j$::jsonb where name='별내커뮤니티센터';
update public.pools set price_free_swim=3600, prices=$j$[{"label": "평일", "amount": 3600}, {"label": "주말", "amount": 4600}]$j$::jsonb where name='오남체육문화센터';
update public.pools set price_free_swim=3600, prices=$j$[{"label": "평일", "amount": 3600}, {"label": "주말", "amount": 4600}]$j$::jsonb where name='와부체육문화센터';
update public.pools set price_free_swim=3600, prices=$j$[{"label": "평일", "amount": 3600}, {"label": "주말", "amount": 4600}]$j$::jsonb where name='진접체육문화센터';
update public.pools set price_free_swim=3600, prices=$j$[{"label": "평일", "amount": 3600}, {"label": "주말", "amount": 4600}]$j$::jsonb where name='호평체육문화센터';
update public.pools set price_free_swim=3600, prices=$j$[{"label": "평일", "amount": 3600}, {"label": "주말", "amount": 4600}]$j$::jsonb where name='화도체육문화센터';
update public.pools set price_free_swim=4730, prices=$j$[{"label": "1일권", "amount": 4730}]$j$::jsonb where name='시립노원청소년센터';
update public.pools set price_free_swim=3900, prices=$j$[{"label": "평일", "amount": 3900}, {"label": "1일권", "amount": 5000}]$j$::jsonb where name='월계구민체육센터';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "평일", "amount": 4000}, {"label": "주말", "amount": 5200}]$j$::jsonb where name='도봉동실내스포츠센터';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "1일권", "amount": 4000}, {"label": "1일권", "amount": 5200}]$j$::jsonb where name='창동문화체육센터';
update public.pools set price_free_swim=3700, prices=$j$[{"label": "평일", "amount": 3700}, {"label": "주말", "amount": 4800}]$j$::jsonb where name='동대문구민체육센터';
update public.pools set price_free_swim=4400, prices=$j$[{"label": "평일", "amount": 4400}, {"label": "주말", "amount": 5700}]$j$::jsonb where name='동작구민체육센터';
update public.pools set price_free_swim=4400, prices=$j$[{"label": "평일", "amount": 4400}, {"label": "주말", "amount": 5700}]$j$::jsonb where name='동작삼일수영장';
update public.pools set price_free_swim=4400, prices=$j$[{"label": "평일", "amount": 4400}, {"label": "주말", "amount": 5700}]$j$::jsonb where name='사당문화회관';
update public.pools set price_free_swim=4800, prices=$j$[{"label": "1일권", "amount": 4800}, {"label": "1일권", "amount": 6200}]$j$::jsonb where name='서울여성플라자스포츠센터';
update public.pools set price_free_swim=4400, prices=$j$[{"label": "평일", "amount": 4400}, {"label": "주말", "amount": 5700}]$j$::jsonb where name='흑석체육센터';
update public.pools set price_free_swim=3500, prices=$j$[{"label": "평일", "amount": 3500}, {"label": "주말", "amount": 4200}, {"label": "평일", "amount": 3000}, {"label": "주말", "amount": 3600}]$j$::jsonb where name='마포아트센터';
update public.pools set price_free_swim=4500, prices=$j$[{"label": "1일권", "amount": 4500}, {"label": "1일권", "amount": 5000}]$j$::jsonb where name='미추홀구국민체육센터';
update public.pools set price_free_swim=3500, prices=$j$[{"label": "1일권", "amount": 3500}]$j$::jsonb where name='부평국민체육센터';
update public.pools set price_free_swim=5000, prices=$j$[{"label": "1일권", "amount": 5000}]$j$::jsonb where name='부평남부체육센터';
update public.pools set price_free_swim=6000, prices=$j$[{"label": "1일권", "amount": 6000}]$j$::jsonb where name='인천북부교육문화센터';
update public.pools set price_free_swim=3500, prices=$j$[{"label": "평일", "amount": 3500}, {"label": "1일권", "amount": 4500}]$j$::jsonb where name='서대문문화체육회관';
update public.pools set price_free_swim=3300, prices=$j$[{"label": "평일", "amount": 3300}, {"label": "주말", "amount": 5500}]$j$::jsonb where name='방배열린문화센터';
update public.pools set price_free_swim=5500, prices=$j$[{"label": "평일", "amount": 5500}, {"label": "공휴일", "amount": 6000}, {"label": "평일", "amount": 4000}, {"label": "공휴일", "amount": 5000}]$j$::jsonb where name='서초종합체육관';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "평일", "amount": 3000}, {"label": "주말", "amount": 3600}]$j$::jsonb where name='판교스포츠센터';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "평일", "amount": 3000}, {"label": "주말", "amount": 3600}]$j$::jsonb where name='황새울국민체육센터';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "평일", "amount": 4000}, {"label": "1일권", "amount": 5300}]$j$::jsonb where name='마장국민체육센터';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "1일권", "amount": 4000}]$j$::jsonb where name='성동구립용답체육센터';
update public.pools set price_free_swim=5300, prices=$j$[{"label": "1일권", "amount": 5300}]$j$::jsonb where name='성동구민종합체육센터';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "1일권", "amount": 4000}]$j$::jsonb where name='열린금호교육문화관';
update public.pools set price_free_swim=4500, prices=$j$[{"label": "평일", "amount": 4500}, {"label": "공휴일", "amount": 5500}]$j$::jsonb where name='개운산스포츠센터';
update public.pools set price_free_swim=5000, prices=$j$[{"label": "평일", "amount": 5000}, {"label": "주말", "amount": 5700}]$j$::jsonb where name='물빛수영장';
update public.pools set price_free_swim=4500, prices=$j$[{"label": "평일", "amount": 4500}, {"label": "주말", "amount": 5500}]$j$::jsonb where name='성북종합레포츠타운';
update public.pools set price_free_swim=5000, prices=$j$[{"label": "1일권", "amount": 5000}]$j$::jsonb where name='송파구체육문화회관';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "평일", "amount": 4000}, {"label": "1일권", "amount": 5200}]$j$::jsonb where name='잠실종합운동장 제1수영장';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "1일권", "amount": 4000}]$j$::jsonb where name='장안구민회관 푸르내 수영장';
update public.pools set price_free_swim=5000, prices=$j$[{"label": "1일권", "amount": 5000}]$j$::jsonb where name='청소년문화센터 수영장';
update public.pools set price_free_swim=3600, prices=$j$[{"label": "1일권", "amount": 3600}]$j$::jsonb where name='능곡 어울림센터';
update public.pools set price_free_swim=3600, prices=$j$[{"label": "1일권", "amount": 3600}]$j$::jsonb where name='시흥 어울림 국민체육센터';
update public.pools set price_free_swim=3600, prices=$j$[{"label": "1일권", "amount": 3600}]$j$::jsonb where name='시흥시국민체육센터';
update public.pools set price_free_swim=600, prices=$j$[{"label": "1일권", "amount": 600}, {"label": "1일권", "amount": 3000}, {"label": "1일권", "amount": 4500}]$j$::jsonb where name='대부동복지체육센터수영장';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}, {"label": "1일권", "amount": 4500}]$j$::jsonb where name='안산 선부다목적체육관수영장';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}, {"label": "1일권", "amount": 4500}]$j$::jsonb where name='안산 신길수영장/목욕탕';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}, {"label": "1일권", "amount": 4500}]$j$::jsonb where name='안산 호수공원실내수영장';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}, {"label": "1일권", "amount": 4500}]$j$::jsonb where name='안산올림픽기념관수영장';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}]$j$::jsonb where name='서안성체육센터 수영장';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}]$j$::jsonb where name='안성국민체육센터 수영장';
update public.pools set price_free_swim=3300, prices=$j$[{"label": "1일권", "amount": 3300}]$j$::jsonb where name='박달복합청사수영장';
update public.pools set price_free_swim=3300, prices=$j$[{"label": "1일권", "amount": 3300}]$j$::jsonb where name='안양실내체육관 수영장';
update public.pools set price_free_swim=3300, prices=$j$[{"label": "1일권", "amount": 3300}]$j$::jsonb where name='호계복합청사 수영장';
update public.pools set price_free_swim=3520, prices=$j$[{"label": "1일권", "amount": 3520}]$j$::jsonb where name='양주국민체육센터 실내수영장';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}]$j$::jsonb where name='서부여성발전센터';
update public.pools set price_free_swim=3500, prices=$j$[{"label": "1일권", "amount": 3500}]$j$::jsonb where name='신월문화체육센터';
update public.pools set price_free_swim=3500, prices=$j$[{"label": "1일권", "amount": 3500}]$j$::jsonb where name='양천구민체육센터';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}]$j$::jsonb where name='양서에코힐링센터 수영장';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}]$j$::jsonb where name='여성회관실내수영장';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "1일권", "amount": 4000}]$j$::jsonb where name='국민체육센터 수영장';
update public.pools set price_free_swim=3500, prices=$j$[{"label": "1일권", "amount": 3500}]$j$::jsonb where name='여주노인복지회관수영장';
update public.pools set price_free_swim=4050, prices=$j$[{"label": "1일권", "amount": 4050}, {"label": "1일권", "amount": 4500}]$j$::jsonb where name='송도체육센터';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}]$j$::jsonb where name='연천군 청소년수련관수영장';
update public.pools set price_free_swim=4400, prices=$j$[{"label": "평일", "amount": 4400}, {"label": "1일권", "amount": 5700}]$j$::jsonb where name='신길종합사회복지관';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "평일", "amount": 4000}, {"label": "주말", "amount": 4500}]$j$::jsonb where name='영등포 제1스포츠센터';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "평일", "amount": 3000}, {"label": "주말", "amount": 4500}]$j$::jsonb where name='영등포 제2스포츠센터';
update public.pools set price_free_swim=3500, prices=$j$[{"label": "1일권", "amount": 3500}]$j$::jsonb where name='세교복지타운수영장';
update public.pools set price_free_swim=3500, prices=$j$[{"label": "1일권", "amount": 3500}]$j$::jsonb where name='오산스포츠센터수영장';
update public.pools set price_free_swim=3500, prices=$j$[{"label": "1일권", "amount": 3500}]$j$::jsonb where name='원동초스포츠센터';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "평일", "amount": 4000}, {"label": "1일권", "amount": 4400}]$j$::jsonb where name='용산청소년센터';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "1일권", "amount": 4000}]$j$::jsonb where name='남사스포츠센터';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "1일권", "amount": 4000}]$j$::jsonb where name='용인시청소년수련관 수영장';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "평일", "amount": 4000}, {"label": "주말", "amount": 5000}]$j$::jsonb where name='은평구민체육센터';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "1일권", "amount": 4000}, {"label": "1일권", "amount": 5000}]$j$::jsonb where name='은평청여울 수영장';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "평일", "amount": 4000}, {"label": "주말", "amount": 5000}]$j$::jsonb where name='은평통일로스포츠센터';
update public.pools set price_free_swim=3900, prices=$j$[{"label": "1일권", "amount": 3900}]$j$::jsonb where name='의정부시 스포츠센터실내수영장';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}]$j$::jsonb where name='의정부시청소년회관 실내수영장';
update public.pools set price_free_swim=5000, prices=$j$[{"label": "1일권", "amount": 5000}]$j$::jsonb where name='이천스포츠센터';
update public.pools set price_free_swim=4500, prices=$j$[{"label": "1일권", "amount": 4500}, {"label": "1일권", "amount": 5000}]$j$::jsonb where name='동구문화체육센터';
update public.pools set price_free_swim=4700, prices=$j$[{"label": "1일권", "amount": 4700}]$j$::jsonb where name='서울시립망우청소년센터';
update public.pools set price_free_swim=4300, prices=$j$[{"label": "1일권", "amount": 4300}]$j$::jsonb where name='중랑구민체육센터';
update public.pools set price_free_swim=3700, prices=$j$[{"label": "평일", "amount": 3700}, {"label": "주말", "amount": 4300}]$j$::jsonb where name='중랑문화체육관';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "평일", "amount": 4000}, {"label": "주말", "amount": 5000}]$j$::jsonb where name='교하청석스포츠센터 수영장';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "평일", "amount": 4000}, {"label": "주말", "amount": 5000}]$j$::jsonb where name='운정다목적체육관 수영장';
update public.pools set price_free_swim=5000, prices=$j$[{"label": "1일권", "amount": 5000}]$j$::jsonb where name='코오롱스포렉스 운정행복점';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "평일", "amount": 4000}, {"label": "주말", "amount": 5000}]$j$::jsonb where name='파주문화체육센터';
update public.pools set price_free_swim=4000, prices=$j$[{"label": "평일", "amount": 4000}, {"label": "주말", "amount": 5000}]$j$::jsonb where name='파주시 스포츠센터 수영장';
update public.pools set price_free_swim=3300, prices=$j$[{"label": "1일권", "amount": 3300}]$j$::jsonb where name='서평택국민체육센터 실내수영장';
update public.pools set price_free_swim=3300, prices=$j$[{"label": "1일권", "amount": 3300}]$j$::jsonb where name='소사벌레포츠타운 수영장';
update public.pools set price_free_swim=3300, prices=$j$[{"label": "1일권", "amount": 3300}]$j$::jsonb where name='이충문화체육센터 실내수영장';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}]$j$::jsonb where name='동탄복합문화센터내 실내수영장';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}]$j$::jsonb where name='동탄중앙어울림센터';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}]$j$::jsonb where name='모두누림센터';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}]$j$::jsonb where name='반월체육센터';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}]$j$::jsonb where name='화성국민체육센터수영장';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}]$j$::jsonb where name='화성남부국민체육센터';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}]$j$::jsonb where name='화성시 그린환경센터 주민편익시설';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}]$j$::jsonb where name='화성시 여성청소년 수련관(유앤아이센터)';
update public.pools set price_free_swim=3000, prices=$j$[{"label": "1일권", "amount": 3000}]$j$::jsonb where name='화성시근로자종합복지관';
